apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
        type: LoadBalancer
      containers:
      - name: nginx
        image: 876594438092.dkr.ecr.us-east-1.amazonaws.com/python:latest 
        ports:
        - containerPort: 5000 
